# Generated by Django 4.1.6 on 2023-04-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='Game', max_length=25)),
                ('updated', models.DateField(auto_now_add=True)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('game_mechanism', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('steam_link', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.FileField(upload_to='game_thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='game_gallery')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery', to='game.game')),
            ],
        ),
    ]
