# Generated by Django 4.1.6 on 2023-05-04 04:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
